### ISSUE TITLE
Could not resolve org.scoverage:scalac-scoverage-plugin_2:1.3.1

### ISSUE THREAD

**Issue by johanneshiry** [scoverage/gradle-scoverage#109]
Hi,

I got an error when I tried to apply the plugin to one of my projects, that files for configuration ':scoverage' could not be resolved. 

**error message (excluded unrelated stuff)**
```
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':scoverage'.
...
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.scoverage:scalac-scoverage-plugin_2:1.3.1.
Required by:
    project :
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.scoverage:scalac-scoverage-plugin_2:1.3.1.
```

**project:** mixed scala / java
**gradle version:** 5.4.1
**scala version:** 2.13
**java version:** 1.8

**plugins in build.gradle:**
```
plugins {
    id "com.jfrog.artifactory" version "4.9.7"
    id 'groovy' // groovy support
    id 'java' // java support
    id 'scala' // scala support
    id 'application' // creates a JVM executable
    id 'maven-publish' // publish to a maven repo (local or mvn central, has to be defined)
    id 'pmd' // code check, working on source code
    id 'com.github.spotbugs' version '2.0.0' // code check, working on byte code
    id 'com.diffplug.gradle.spotless' version '3.23.0'// code format
    id 'com.simonharrer.modernizer' version '1.6.0-1' // detect deprecated APIs
    id 'com.github.onslip.gradle-one-jar' version '1.0.5' // pack a self contained jar
    id "de.undercouch.download" version "3.4.3" // downloads plugin
    id "kr.motd.sphinx" version "2.5.0" // documentation generation
    id "com.github.johnrengelman.shadow" version "5.1.0" // fat jar
    id 'jacoco' // java code coverage plugin
    id "org.scoverage" version "3.1.5"
}
```

**repositories in build.gradle:**
```
repositories {
    mavenLocal() //searches in local maven repository, typically ~/.m2/repository
    jcenter() //searches in bintray's repository 'jCenter', which contains Maven Central
    maven { url '<internal repo url>' }
    maven { url 'https://jade.tilab.com/maven/' } // Maven repository for jade
    maven { url 'https://jitpack.io' } // allows github repos as dependencies
}
```

If you need a full config or more information, please let me know.

Thanks,

Johannes

**Comment by eyalroth** [comment]
It looks like the scalac plugin version `1.3.1` is not available for Scala `2.13`: https://mvnrepository.com/artifact/org.scoverage/scalac-scoverage-plugin

Try using the `1.4.0` version instead (instructions [in the readme](https://github.com/scoverage/gradle-scoverage#configuration)), though I'm not sure this (gradle) plugin is compatible with that version of the scalac plugin.

**Comment by johanneshiry** [comment]
Thanks for the fast reply. I added the scoverage block as follows: 

```
scoverage {
	scoverageVersion = "1.4.0"
}
```

Now I get an alike error but with the changed version: 

```
Caused by: org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':scoverage'.
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.rethrowFailure(DefaultConfiguration.java:1258)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.access$2200(DefaultConfiguration.java:139)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:1233)
	at org.gradle.api.internal.file.AbstractFileCollection.iterator(AbstractFileCollection.java:75)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.iterator(DefaultConfiguration.java:486)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:1011)
	at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:994)
	at org.codehaus.groovy.runtime.InvokerHelper.asIterator(InvokerHelper.java:591)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.find(DefaultGroovyMethods.java:4292)
	at org.codehaus.groovy.runtime.dgm$218.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoMetaMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:223)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:70)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at org.scoverage.ScoveragePlugin$_createTasks_closure6$_closure17.doCall(ScoveragePlugin.groovy:222)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at groovy.lang.Closure.call(Closure.java:427)
	at org.gradle.util.ClosureBackedAction.execute(ClosureBackedAction.java:71)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:154)
	at org.gradle.util.ConfigureUtil.configureSelf(ConfigureUtil.java:130)
	at org.gradle.api.internal.AbstractTask.configure(AbstractTask.java:587)
	at org.gradle.api.Task$configure$4.call(Unknown Source)
	at org.scoverage.ScoveragePlugin$_createTasks_closure6.doCall(ScoveragePlugin.groovy:220)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1$1.run(DefaultListenerBuildOperationDecorator.java:185)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext.reapply(DefaultUserCodeApplicationContext.java:60)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure$1.run(DefaultListenerBuildOperationDecorator.java:180)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
	at org.gradle.configuration.internal.DefaultListenerBuildOperationDecorator$BuildOperationEmittingClosure.doCall(DefaultListenerBuildOperationDecorator.java:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at groovy.lang.Closure.call(Closure.java:411)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:41)
	at org.gradle.listener.ClosureBackedMethodInvocationDispatch.dispatch(ClosureBackedMethodInvocationDispatch.java:25)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:231)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:150)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:325)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:235)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:141)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy34.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:191)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate$1.execute(LifecycleProjectEvaluator.java:188)
	at org.gradle.api.internal.project.DefaultProject.stepEvaluationListener(DefaultProject.java:1420)
	at org.gradle.configuration.project.LifecycleProjectEvaluator$NotifyAfterEvaluate.run(LifecycleProjectEvaluator.java:197)
	... 118 more
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve org.scoverage:scalac-scoverage-plugin_2:1.4.0.
```

**Comment by eyalroth** [comment]
The `scala-library` dependency should be defined with its full version; i.e `2.13.0` instead of `2.13`.

When the dependency is defined the plugin ignores the `scoverageScalaVersion` option and interprets Scala's version according to the dependency version, and it expects a full version definition.

**Comment by johanneshiry** [comment]
Changing `2.13`to `2.13.0` did the trick and it _seems_ working now. (Caused another error with a different gradle plugin but I was able to solve that)

Don't have time to try the full functionality right now, but I will check this in the next 24h and report back if it's fully working now. 

Thank you very much for your help!

**Comment by maiflai** [comment]
For what it's worth, 1.4.0 support is pending a couple of upstream changes - https://github.com/scoverage/gradle-scoverage/pull/107 will be updated when they are available.

**Comment by johanneshiry** [comment]
Just wanted to let you know, that it doesn't fully work yet. :-(  
I'm able to execute  `gradle reportTestScoverage` but it fails. 

**Stacktrace (unrelevant stuff excluded):**
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':reportTestScoverage'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)

Caused by: java.lang.NoClassDefFoundError: scala/collection/JavaConversions
        at org.scoverage.ScoverageReport$_report_closure1.doCall(ScoverageReport.groovy:51)
        at org.scoverage.ScoverageReport$_report_closure1.doCall(ScoverageReport.groovy)
        at org.scoverage.ScoverageRunner.run(ScoverageRunner.groovy:30)
        at org.scoverage.ScoverageRunner$run.call(Unknown Source)
        at org.scoverage.ScoverageReport.report(ScoverageReport.groovy:42)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
```

scala.collection.JavaConversions is deprecated since scala 2.13.0 but still available. I'm wondering if there is anything inside gradle that holds back using pieces of code that are marked as deprecated?

Dunno if this is scoverage-plugin related or a missconfiguration on my side. If you have any thoughts on this I would be happy to read them.

**Comment by eyalroth** [comment]
I just tried adding a functional test for Scala 2.13 and I got this error:
```
Compat.scala:152: error: postfix operator headOption needs to be enabled
```

It might be that Scala 2.13 isn't working properly with Gradle at the moment. See https://github.com/gradle/gradle/issues/9857.

**Comment by eyalroth** [comment]
Yeah it seems that `JavaConversions` is no longer available in Scala 2.13 (and `JavaConverters` is deprecated): https://docs.scala-lang.org/overviews/core/collections-migration-213.html (Look for the "Deprecated things in 2.12 that have been removed in 2.13" section)

@maiflai I'm wondering why have we switched away from `JavaConverters`. It should be backward-compatible with Scala 2.11.8.

**Comment by eyalroth** [comment]
It looks like version `1.4.0` of the  scalac plugin is definitely not compatible with the current version of the gradle plugin (not just for Scala 2.13).

I'm tracking at least one breaking change where the 'IOUtils.reportFileSearch' -- used by the gradle plugin -- was removed and replaced by `IOUtils.scoverageDataDirsSearch`. See https://github.com/scoverage/scalac-scoverage-plugin/pull/241.

We need to first make this plugin work with `1.4.0` and only then we can also fix the compatibility with 2.13, which seems to be rather simple.

**Comment by johanneshiry** [comment]
Are there any updates on this issue or https://github.com/scoverage/gradle-scoverage/issues/106?

**Comment by maiflai** [comment]
Sorry, we’re still waiting on a 1.4.1 release of the scalac plugin.

**Comment by johanneshiry** [comment]
Can confirm that the plugin works now (at least the issue here is resolved). Now I'm struggling with a different, already reported issue. I added specific information in the corresponding issue thread here https://github.com/scoverage/gradle-scoverage/issues/98
